version: '3.7'
services:
  auth:
    container_name: auth
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - server.profile=dev
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379